services:
  db:
    image: postgres:16
    container_name: InventoryNexus-Postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql
      - ./init-db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  vault:
    image: hashicorp/vault:1.21.3
    container_name: InventoryNexus-Vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_TOKEN: ${DEV_TOKEN}
      VAULT_DEV_LISTEN_ADDR: "0.0.0.0:8200"
      VAULT_ADDR: "http://127.0.0.1:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vaultdata:/vault/file
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]
    command:
      - server
      - -dev
      - -dev-root-token-id=${DEV_TOKEN}
      - -dev-listen-address=0.0.0.0:8200
    healthcheck:
      test: ["CMD", "sh", "-c", "vault status -address=http://127.0.0.1:8200 2>&1 | grep -q 'Initialized.*true'"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
  vault-init:
    image: hashicorp/vault:1.21.3
    container_name: InventoryNexus-Vault-Init
    restart: "no"
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: ${DEV_TOKEN}
    env_file: .env
    volumes:
      - ./init-vault/00-init-secrets.sh:/vaultdata/scripts/00-init-secrets.sh
    entrypoint: ["/bin/sh", "/vaultdata/scripts/00-init-secrets.sh"]
    depends_on:
      vault:
          condition: service_healthy
  key-cloak:
    image: quay.io/keycloak/keycloak:26.5
    container_name: InventoryNexus-KeyCloak
    command:
     - start-dev
     - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_IMPORT: /opt/keycloak/data/import/InventoryNexus-realm.json

      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_DATABASE: ${DB_NAME}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8180

      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    ports:
      - "8180:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./keycloak-export:/opt/keycloak/data/import






volumes:
  pgdata:
  vaultdata:
